blind_theme:
    resource: "@BlindBundle/Resources/config/routing/theme.yml"
    prefix:   /theme

blind_tournoi:
    resource: "@BlindBundle/Resources/config/routing/tournoi.yml"
    prefix:   /tournoi

blind_homepage:
    path:     /
    defaults: { _controller: BlindBundle:Tournoi:index }

tournoi_index:
    path:     /index
    defaults: { _controller: BlindBundle:Tournoi:index }

tournoi_create:
    path:     /create
    defaults: { _controller: BlindBundle:Tournoi:new }